name: Submit New Faucet
description: Submit a new faucet
title: "[NEW]: "
labels: ["NEW"]
assignees:
  - xrdavies
  - wendychaung
body:
  - type: input
    id: Name
    attributes:
      label: The name of the faucet
      description: What is the name of the faucet
      placeholder: Tell us the name!
    validations:
      required: true
  - type: input
    id: Link
    attributes:
      label: The link of the faucet
      description: What is the link of this faucet
      placeholder: ex. https://gitter.im/kovan-testnet/faucet
    validations:
      required: true
  - type: input
    id: logo
    attributes:
      label: The link of logo for the tool/resource
      description: What is the logo link for this tool/resource?
      placeholder: Tell us the link!
    validations:
      required: true
